// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsMWo6sHGkoYMT7zqeLoBEBogTts3RIO8',
    appId: '1:805597973259:android:799c6a2424185fea95300e',
    messagingSenderId: '805597973259',
    projectId: 'shop-app-d988a',
    databaseURL: 'https://shop-app-d988a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-d988a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUb0HH10d51wSlaM03zpNbfr5-TMQeTr8',
    appId: '1:805597973259:ios:d7930b1bbda260ad95300e',
    messagingSenderId: '805597973259',
    projectId: 'shop-app-d988a',
    databaseURL: 'https://shop-app-d988a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-d988a.appspot.com',
    iosBundleId: 'com.example.bruhmius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUb0HH10d51wSlaM03zpNbfr5-TMQeTr8',
    appId: '1:805597973259:ios:d7930b1bbda260ad95300e',
    messagingSenderId: '805597973259',
    projectId: 'shop-app-d988a',
    databaseURL: 'https://shop-app-d988a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-d988a.appspot.com',
    iosBundleId: 'com.example.bruhmius',
  );

}